### PR TITLE
Make ES5 compatible

### LINKED ISSUE #73: ES5 compatibility
Currently we use ES modules, but they cannot be used by older node projects. 

Therefore, it would be useful to transpile the code to ES5

### PR DESCRIPTION
**Pull request by JakobMiksch**
fixes #73

This PR attempts to make `geoserver-node-client` compatible to ES5.

- Note: importing the library via git does **not** work for ES5: 
```json
"geoserver-node-client": "git+https://github.com/jakobmiksch/geoserver-node-client.git"
```

### TODO:

- [x] ensure it works in combination with `release-it`, fixed with https://github.com/meggsimum/geoserver-node-client/commit/e1910ad0f675e0ee7a873bbc62fe53cec0bbb40d
- [x] ~~include ES5 version in CI tests --> Issue~~ moved to https://github.com/meggsimum/geoserver-node-client/issues/82

### CODE REVIEW

**Comment by JakobMiksch** [comment]
@chrismayer this commit https://github.com/meggsimum/geoserver-node-client/pull/80/commits/e1910ad0f675e0ee7a873bbc62fe53cec0bbb40d should ensure that `release-it` also builds the ESM5 compatible code. 
I tested it with the dry run functinality: `npx release-it --dry-run` and the produced commands looked like expected (see below). So, I am optimistic that it will work in production as well.

```
? Select increment (next version): patch (0.0.8)
! npm version 0.0.8 --no-git-tag-version
! npm run build                                    <-- HERE RELEASE-IT TRIGGERS THE BUILT
$ git status --short --untracked-files=no

Empty changeset

! git add . --update
? Publish geoserver-node-client to npm? Yes
$ npm publish . --tag latest --dry-run
? Commit (Release 0.0.8)? Yes
! git commit --message Release 0.0.8
? Tag (0.0.8)? Yes
! git tag --annotate --message Release 0.0.8 0.0.8
? Push? Yes
$ git symbolic-ref HEAD  [cached]
$ git for-each-ref --format="%(upstream:short)" refs/heads/esm-approach  [cached]
! git push --follow-tags
🔗 https://www.npmjs.com/package/geoserver-node-client
🏁 Done (in 27s.)
```

**Comment by JakobMiksch** [comment]
@chrismayer the commit https://github.com/meggsimum/geoserver-node-client/pull/80/commits/9a66c88bca5e8b038635b5eb6d19c13728ffa816 also exposes the GeoServerResponseError to the user of the library. This can be useful to perform error handling based on different kinds of errors. Similar to the code below. Does this make sense to you?

```js
try {
  myroutine(); // may throw three types of exceptions
} catch (e) {
  if (e instanceof TypeError) {
    // statements to handle TypeError exceptions
  } else if (e instanceof RangeError) {
    // statements to handle RangeError exceptions
  } else if (e instanceof EvalError) {
    // statements to handle EvalError exceptions
  } else {
    // statements to handle any unspecified exceptions
    logMyErrors(e); // pass exception object to error handler
  }
}

```
(taken from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#conditional_catch-blocks )

**Comment by chrismayer** [comment]
> exposes the GeoServerResponseError to the user of the library. This can be useful to perform error handling based on different kinds of errors. Similar to the code below. Does this make sense to you?

Yes, makes totally sense. +1 for this. We just have to clarify where the export itself should be placed best. See my comment here https://github.com/meggsimum/geoserver-node-client/commit/9a66c88bca5e8b038635b5eb6d19c13728ffa816#r74009863

**Comment by JakobMiksch** [comment]
@chrismayer I responded to your comment inline.

**Comment by chrismayer** [comment]
Since the Error stuffe is moved to a separate PR (#83) this is good to go.

**Pull request merged**
