### PR TITLE
Update libs

### PR DESCRIPTION
**Pull request by hblitza**
- general update of npm libs
- geoserver stable rotation

@chrismayer :pray:

### CODE REVIEW

**Comment by hblitza** [comment]
Just saw this issue https://github.com/meggsimum/geoserver-node-client/issues/128

**Comment by chrismayer** [comment]
I fear yes...by stating that we support GeoServer 2.23 we have a breaking change in the library since GeoServer apparently changed the API (see #128). So I'd suggest to either split this PR and seperate the update of npm dependecies so we can easily postpone the GeoServer version rotation. Or you leave the PR as it is and we wait for the merge until GeoServer 2.22 has reached its end of life. 

What do you think @hblitza ?

**Comment by chrismayer** [comment]
`DOCS_HOME.md` needs also an update, if we stick to GeoServer version rotation in here.

**Comment by chrismayer** [comment]
@hblitza since I created a PR (#130) to fix #128 we could do the GeoServer rotation in here and merge this once #130 is merged and you updated the `DOCS_HOME.md`.

**Comment by hblitza** [comment]
@chrismayer please check

**Review by chrismayer — APPROVED** [review]

**Comment by chrismayer** [comment]
Thanks for this @hblitza , I am going to merge now.

**Pull request merged**
