### PR TITLE
Add createGeotiffFromStream method

### PR DESCRIPTION
**Pull request by cesco69**

### CODE REVIEW

**Review by chrismayer — COMMENTED** [review]
Thanks for your contribution @cesco69 It is very much appreciated. 2 questions/remarks

Does the GeoTiff have to be at the server as file? Or is it possible to send an arbitrary GeoTiff readStream by using the new function  `createGeotiffFromStream`? Within the API docs of the function it states `"The GeoTIFF file has to be placed on the server, where your GeoServer is running."` Maybe copy/paste of the old API docs or has the GeoTiff still to be available on the server?

Line 194 is now unnecessary and can be removed, since you pass `layerName` and `layerTitle` to the `createGeotiffFromStream` function.

**Comment by cesco69** [comment]
> Does the GeoTiff have to be at the server as file? Or is it possible to send an arbitrary GeoTiff readStream by using the new function createGeotiffFromStream? 

You can send to  GeoServer API an arbitrary readStream, but GeoServer still store the stream on the server where is running.

> Within the API docs of the function it states "The GeoTIFF file has to be placed on the server, where your GeoServer is running." > Maybe copy/paste of the old API docs or has the GeoTiff still to be available on the server?

The docs is correct, the stream is stored on the server where GeoServer is running.

**Comment by chrismayer** [comment]
Thanks for the clarification and the follow-up commit. Looks good to me and I am going to merge now.

**Comment by cesco69** [comment]
Thanks for the merge @chrismayer ! Just a question, when planning to release a new version?

**Comment by chrismayer** [comment]
I just release the new version [1.3.0](https://github.com/meggsimum/geoserver-node-client/releases/tag/v1.3.0)

**Pull request merged**
