### PR TITLE
Refactor authentication and url handling

### PR DESCRIPTION
**Pull request by JakobMiksch**
- ~~depends on #46 and should be merged afterwards~~
- targets #48

- The authentication used to be created in every single function `'Basic ' + Buffer.from(user + ':' + password).toString('base64');`. This PR creates it only once in `geoserver-rest-client.js` and forwards it to its dependent sub-classes - [CHANGES](https://github.com/meggsimum/geoserver-node-client/pull/51/commits/97c6cfc3c58b202bf9f83eb17219120b2950e08c)
- the main constructor validates the URL `url.endsWith('/') ? url : url + '/'` for a good reason. However this is done again in all dependent sub-classes. This PR removes the redundant validations - [CHANGES](https://github.com/meggsimum/geoserver-node-client/pull/51/commits/a2f82a000be0f151a8505d8c20be30062cd9b339)

### CODE REVIEW

**Comment by JakobMiksch** [comment]
@chrismayer this is ready to get reviewed again

**Comment by chrismayer** [comment]
@JakobMiksch Please rebase after #46 is merged. Then I'll have a look.

**Comment by JakobMiksch** [comment]
@chrismayer this PR is rebased and ready for review
It is now part of a project board for Version 1.0
https://github.com/meggsimum/geoserver-node-client/projects/1

**Review by chrismayer — APPROVED** [review]
NIce refactoring, LGTM. Please merge at will...

**Pull request merged**
